fix: typo bash

diff --git a/.github/workflows/gladia-builder.yml b/.github/workflows/gladia-builder.yml
--- a/.github/workflows/gladia-builder.yml
+++ b/.github/workflows/gladia-builder.yml
@@ -107,11 +107,12 @@ jobs:
           tryInit=200
           while [[ $(/tmp/kubectl -n gladia-test-aipi get pod aipi-test-${{env.DOCKER_BUILD_TAG}} -o=jsonpath='{.status.conditions[?(@.type=="PodScheduled")].status}') != "False" ]]; do
               if [ $tryInit -eq 0 ]; then
-                  printf "\nError: TIme out trying to scheduled the test pod. We might be out of GPUs. Retry and/or contact your favorite DevOps <3."
-                  exit 1
+                printf "\nError: TIme out trying to scheduled the test pod. We might be out of GPUs. Retry and/or contact your favorite DevOps <3."
+                exit 1
+              fi
               if [[ $(/tmp/kubectl -n gladia-test-aipi get pod aipi-test-${{env.DOCKER_BUILD_TAG}}) =~ "NotFound" ]]
-                  printf "\nError: Test pod disappeared while being scheduled. It probably failed to start. Check logs and/or test your build manually."
-                  exit 1
+                printf "\nError: Test pod disappeared while being scheduled. It probably failed to start. Check logs and/or test your build manually."
+                exit 1
               fi
               printf "."
               ((tryInit--))
@@ -121,11 +122,12 @@ jobs:
           tryReady=200
           while [[ $(/tmp/kubectl -n gladia-test-aipi get pod aipi-test-${{env.DOCKER_BUILD_TAG}} -o=jsonpath='{.status.conditions[?(@.type=="Ready")].status}') != "False" ]]; do
               if [ $tryReady -eq 0 ]; then
-                  printf "\nError: Test pod timed out while waiting for readyness. Check logs and/or test your build manually."
-                  exit 1
+                printf "\nError: Test pod timed out while waiting for readyness. Check logs and/or test your build manually."
+                exit 1
+              fi
               if [[ $(/tmp/kubectl -n gladia-test-aipi get pod aipi-test-${{env.DOCKER_BUILD_TAG}}) =~ "NotFound" ]]
-                  printf "\nError: Test pod disappeared while starting. Check logs and/or test your build manually."
-                  exit 1
+                printf "\nError: Test pod disappeared while starting. Check logs and/or test your build manually."
+                exit 1
               fi
               printf "."
               ((tryReady--))
